[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false
resolution = true

[programs.localnet]
# Signer Checks
vulnerable_signer_checks = "6aMtrYT8eeCbtvtfcAEiUfkQAZ9MHVgRipAFKgddC3TD"
secure_signer_checks = "9KLc9xT6Ub25gpr5QvJbcJC2kEH6zCWSEF9s1ZDj7pPb"

# Owner Checks
vulnerable_owner_checks = "5rezfTZ6Hk5RK8gxPLvBC3nsWgcbC7qHB2nr5TioZ9aT"
secure_owner_checks = "6vXq3U6ezSy1yBzFc1nqTdPgXSxkE7vpdEUHUNiYurSN"

# Arbitrary CPI
vulnerable_arbitrary_cpi = "J9nJgXQ2pckccZdRb6zuRXJiupqF7AJN7yFzzJTHepkz"
secure_arbitrary_cpi = "BvjL8mMCaXZ54EnfaFJLPcnx2jFgvtnpCb9XmKoDx3eu"

# Reinitialization Attacks
vulnerable_reinitialization_attacks = "BBQQXUoERwojEV7hSgSCMjsNvmv2nTKkdsMpRHuGXZjT"
secure_reinitialization_attacks = "FRauohhzqgjegAosW6SUNHhPfZFSCHLDfNjVUUBG5ebk"

# Type Cosplay
vulnerable_type_cosplay = "2nRRf2TAjrMenoDDPcmMpsuFc2ithWwYXAm9cg2UUCdx"
secure_type_cosplay = "2aVdRcZRWcmttBdWJR7z9dt47UkSrrdB3Fco1F8yLmcj"

# PDA Sharing
vulnerable_pda_sharing = "4AYMT1uUswxPRdYNxg586mo2gdYrZeEcyx6FunqpZZzR"
secure_pda_sharing = "6dKVUQcDpeq4Sh6a7QkKwW1dBR2BiJPSUFYdYQmPDHJe"

# Bump Seed Canonicalization
vulnerable_bump_seed_canonicalization = "EhLoKK5wYMoU95ibhc6ErhmAb9ELkLTWvqyeJBMAmpx2"
secure_bump_seed_canonicalization = "5RmCKP8aNEDVdDPJwJXUn4icVzq4jti72kSfiBiJj9CJ"

# Integer Overflow
vulnerable_integer_overflow = "FJCcDyRTAEJBFocGJ6UwKMbPobZACyYHFmAv8wTsGsWy"
secure_integer_overflow = "5tnoXzXyE4q84XSKmfuR6ZU1hWEXUHhbwyvhkNjyAxGH"

# Panic Handling
vulnerable_panic_handling = "A5QPcpmFYpkPQdPNhv92vXUZRGWMDsmy1HAy6dj2xKjr"
secure_panic_handling = "BCaMVsHMzC2yT9S6fxEjnWHL7tm2VFk9jMetawEgTh4t"

# Closing Accounts
vulnerable_closing_accounts = "3k6fBqaWzqPmvHWjLrgpHqJx6BbKZ65zksZjAx24oGLz"
secure_closing_accounts = "FtwjVwEqhZXjbMgii9D2EYkTjXyi3xYiejqmzhYDgZM3"

# Unsafe Rust
vulnerable_unsafe_rust = "HC7RbuKNEAZRx7WRhBgaBcYKeNr4fuaZwmo4V1LSCkGz"
secure_unsafe_rust = "UuU4HvUCKQj4d6a2bxWHtsAhoZEw22i9iSunCtYLsHf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.test.ts"

[workspace]
members = [
    "programs/signer-checks/vulnerable/anchor",
    "programs/signer-checks/secure/anchor",
    "programs/owner-checks/vulnerable/anchor",
    "programs/owner-checks/secure/anchor",
    "programs/arbitrary-cpi/vulnerable/anchor",
    "programs/arbitrary-cpi/secure/anchor",
    "programs/reinitialization-attacks/vulnerable/anchor",
    "programs/reinitialization-attacks/secure/anchor",
    "programs/type-cosplay/vulnerable/anchor",
    "programs/type-cosplay/secure/anchor",
    "programs/pda-sharing/vulnerable/anchor",
    "programs/pda-sharing/secure/anchor",
    "programs/bump-seed-canonicalization/vulnerable/anchor",
    "programs/bump-seed-canonicalization/secure/anchor",
    "programs/integer-overflow/vulnerable/anchor",
    "programs/integer-overflow/secure/anchor",
    "programs/panic-handling/vulnerable/anchor",
    "programs/panic-handling/secure/anchor",
    "programs/closing-accounts/vulnerable/anchor",
    "programs/closing-accounts/secure/anchor",
    "programs/unsafe-rust/vulnerable/anchor",
    "programs/unsafe-rust/secure/anchor",
]
